
# ===========================
# Global site settings:
# ===========================

# Main title, displayed in the browser tab and site header.
title: Guilherme Lampert

# Tag-line/short description displayed in the header beside the title.
tag_line: Games Programming

# Alternate tag-line, used as tooltip for the site's logo.
tag_line_alt: Welcome to my personal website

# Write an awesome description for your new site here.
# It will appear in your document head meta (for Google search results)
# Note: The `>` means to ignore newlines until next item ("destination").
description: >
    I use this space to occasionally write about some of my personal projects and other things related to games
    programming and game development. I'm mainly interested in graphics and real-time rendering for games.
    C, C++ and Rust are usually the programming languages I play with.

destination: ./site               # Directory Jekyll outputs to
baseurl:      ""                  # The subpath of your site, e.g. /site/
url:          http://glampert.com # The base hostname & protocol for your site

# Title of the landing page. Presented in the nav-bar.
landing_page: Blog

# Post URL format:
permalink: /:year/:month-:day/:title/

# Number of items in the Blog's post list:
paginate: 10
paginate_path: page:num

# Social-media/contact links and icons displayed at the footer:
email:                  guilherme.ronaldo.lampert@gmail.com
twitter_username:       lampert_g
github_username:        glampert
bitbucket_username:     glampert
stackexchange_username: glampert

# ===========================
# Build settings:
# ===========================

# Markdown engine:
markdown: kramdown

# Syntax highlight plugin:
highlighter: rouge

# Automatic sitemap.xml generator:
jekyll-sitemap: true

plugins:
  - jekyll-sitemap
  - jekyll-paginate

